# Generated by Django 5.2.14 on 2026-05-30 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpprofile',
            name='echis_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chpprofile',
            name='echis_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chpprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chpprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storedcredential',
            name='system',
            field=models.CharField(choices=[('echis', 'eCHIS'), ('dashboard', 'Dashboard'), ('registry', 'Registry'), ('dhhd', 'This App (DHHD)'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('tech_team', 'Tech Team'), ('country', 'Country User'), ('county', 'County User'), ('subcounty', 'SubCounty User'), ('cha', 'CHA')], default='cha', max_length=20),
        ),
        migrations.CreateModel(
            name='CHAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('echis_username', models.CharField(blank=True, max_length=150)),
                ('echis_password', models.CharField(blank=True, max_length=255)),
                ('dashboard_username', models.CharField(blank=True, max_length=150)),
                ('dashboard_password', models.CharField(blank=True, max_length=255)),
                ('registry_username', models.CharField(blank=True, max_length=150)),
                ('registry_password', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chus', models.ManyToManyField(blank=True, related_name='cha_profiles', to='core.chu')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cha_profiles', to='core.subcounty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
