# Generated by Django 5.2.14 on 2026-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chpprofile_echis_password_chpprofile_echis_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
