# Generated by Django 5.2.14 on 2026-06-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_password',
        ),
        migrations.AddField(
            model_name='device',
            name='incident_date',
            field=models.DateField(blank=True, help_text='When did the damage/loss/repair happen?', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='reporting_status',
            field=models.CharField(choices=[('normal', 'Reporting Normally'), ('using_personal', 'Using Personal Phone'), ('not_reporting', 'Not Reporting')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair'), ('lost', 'Lost'), ('replaced', 'Replaced')], default='active', max_length=20),
        ),
    ]
