# Generated by Django 5.2.14 on 2026-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chu',
            options={'ordering': ['name'], 'verbose_name': 'CHU'},
        ),
        migrations.AlterField(
            model_name='chaprofile',
            name='dashboard_username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='chaprofile',
            name='echis_username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='chaprofile',
            name='registry_username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='chpprofile',
            name='echis_username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
