# Generated by Django 5.2.14 on 2026-06-29 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_chu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Article Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app_links/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(blank=True, help_text='Leave blank for links visible to all counties', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_links', to='core.county')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or MP4 link')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.articlecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the week')),
                ('week_end', models.DateField(help_text='Friday of the week')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplans', to='core.chu')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_workplans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='WorkPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('objective', models.TextField(blank=True)),
                ('activity', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('actual_results', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('workplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.workplansubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.TextField(blank=True)),
                ('lesson_2', models.TextField(blank=True)),
                ('lesson_3', models.TextField(blank=True)),
                ('challenge_1', models.TextField(blank=True)),
                ('challenge_2', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('priority_1_objective', models.TextField(blank=True)),
                ('priority_1_activity', models.TextField(blank=True)),
                ('priority_1_output', models.TextField(blank=True)),
                ('priority_2_objective', models.TextField(blank=True)),
                ('priority_2_activity', models.TextField(blank=True)),
                ('priority_2_output', models.TextField(blank=True)),
                ('priority_3_objective', models.TextField(blank=True)),
                ('priority_3_activity', models.TextField(blank=True)),
                ('priority_3_output', models.TextField(blank=True)),
                ('workplan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.workplansubmission')),
            ],
        ),
    ]
